# Generated by Django 5.1 on 2024-09-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='paiement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.paiement'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='abonnement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.abonnement'),
        ),
    ]
