# Generated by Django 5.1 on 2024-09-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_abonnement_paiement_alter_compte_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.paiement'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.abonnement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='paye',
            field=models.CharField(choices=[('NON', 'Non'), ('OUI', 'Oui')], default='Non', max_length=9),
        ),
    ]
