# Generated by Django 5.1 on 2024-09-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_abonnement_paiement_alter_compte_abonnement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='raison',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
