# Generated by Django 4.2.3 on 2024-09-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_paiement_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='paye',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='Non', max_length=9),
        ),
    ]
