# Generated by Django 4.2.3 on 2024-09-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_paiement_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='paye',
            field=models.CharField(choices=[('NON', 'Non'), ('OUI', 'Oui')], default='Non', max_length=9),
        ),
    ]
